#!/usr/bin/env bash
# write a script that changes the IP of localhost to 127.0.0.2 and facebook.com to 8.8.8.8

echo '127.0.0.2       localhost/' /etc/hosts
echo "8.8.8.8        facebook.com" >> /etc/hosts
